Updated example.py
bain3/pronotepy pull request #123
Opened 2022-03-19 08:34 UTC by nouni19

Hello, I updated example.py (and README, only where it shows the example). I added a homework example, and additional comments on the client login successful check. I had to commit twice because I accidentally removed a comment, so sorry for the confusion

2022-03-22 22:35 UTC, bain3 requested changes
Nice! I would keep this in `example.py` but I don't think we need it in the README. It's a bit long. Also please add spaces in the comments after the `#`. Thanks!

2022-03-22 22:35 UTC, bain3 commented on example.py
> +    homework = client.homework(today) #get list of all homework which are for today and after
I'd change the comment to: get list of homework for today or later

2022-03-22 22:35 UTC, bain3 commented on example.py
> +else: #if it didn't log in
I don't think we need a comment here, it's pretty straight forward

2022-03-23 16:10 UTC, nouni19 commented
I updated the PR: reverted README changes, removing the "else:" comment and adding spaces after #s

2022-03-23 20:00 UTC, merged