QR code login
bain3/pronotepy pull request #124
Opened 2022-03-21 22:35 UTC by Bapt5

* Implement login with QR code 🎉 (fix #101)

2022-03-22 22:27 UTC, bain3 requested changes
There's a mypy error but I think it is just the worker not having all deps. Great work! Good non-breaking implementation.

2022-03-22 22:27 UTC, bain3 commented on README.md
> +    print('no login')
I don't think we need the rest...
```suggestion
```

2022-03-23 07:35 UTC, Bapt5 commented
@bain3 I've a question about the roadmap What you mean by `Consistent ENT function naming` and `Split up dataClasses.py` ?

2022-03-23 07:38 UTC, bain3 commented
Afaik ent aren't all called the same. I'd change their name to `ent_something`.

`dataClasses.py` is getting long. Splitting it up is for the best. Making a file for each model for example.

2022-03-23 07:39 UTC, Bapt5 commented
> Afaik ent ne sont pas tous appelés de la même manière. Je changerais leur nom en `ent_something`.
> 
> `dataClasses.py`devient long. Le diviser est pour le mieux. Faire un dossier pour chaque modèle par exemple.

Okay I understand I will do that.

2022-03-23 07:57 UTC, bain3 commented
Oh noo. I think merging the qr login before 3.0.0 is ok. For 3.0.0 I'd like to clean up a bit in general. Can we make this pr only the qr?

2022-03-23 08:00 UTC, Bapt5 commented
Oh excuse me. II was thinking of doing all the possible updates I can do.

2022-03-23 08:00 UTC, Bapt5 commented
I don't know how I can remove my last commit from PR

2022-03-23 08:30 UTC, bain3 commented
Yeah I guess

2022-03-23 08:36 UTC, Bapt5 commented
I create a new branch on my repo to make all change for 3.0.0. It will be simpler

2022-03-23 21:25 UTC, bain3 approved these changes
LGTM

2022-03-23 21:25 UTC, merged