Delete cas without educonnect
bain3/pronotepy pull request #255
Opened 2023-08-19 02:04 UTC by LeGeek01

I have done all the following:

- [x] added the feature
- [ ] added documentation for the feature
- [ ] added tests for the feature
- [ ] ran mypy, black, and unit tests

Suppression des CAS de l'ac Lyon, Geenoble et Clermont-Ferrand car ce mode de connexion a été supprimé du cas Ma classe en Auvergne Rhône Alpes.
La connexion via EduConnect est donc maintenant la seule option de connexion

2023-08-19 02:21 UTC, LeGeek01 commented
J'en ai profité pour check les ents qui avaient supprimé ça, et j'ai supprimé tout ce qui ne marche plus dans mon dernier commit (après essai de connexion cela retourne bien une erreur)

2023-09-02 18:31 UTC, bain3 commented
Hi, thanks for the PR! Can you please also remove `ozecollege_yvelines`? It looks closed. Also please remove the ENTs from the documentation in `docs/source/api/ent.rst`. Thanks!

2023-09-03 13:59 UTC, LeGeek01 commented
c'est tout bon

2023-09-03 14:48 UTC, bain3 requested changes
There are still some differences between the docs and code (for example `ac_rennes` is missing in the docs, but is still in the codebase, I didn't check everything yet). pls fix

2023-09-05 18:03 UTC, LeGeek01 commented
normalement tout est bon cette fois, je vais recheck les ents pour voir si j'en ai pas oublié

2023-09-05 18:15 UTC, LeGeek01 commented
cette fois-ci tout est bon

2023-09-05 19:37 UTC, LeGeek01 commented
Du coup on en est où ?

2023-09-05 20:03 UTC, Bapt5 commented
Tu dois répondre a mon review ou je te demande ce que tu as fait de l'ENT de Rennes

2023-09-05 20:04 UTC, LeGeek01 commented
J'ai pas vu la review

2023-09-05 20:04 UTC, LeGeek01 commented
J'avais retesté les ents, et je crois que celui rennes ne fonctionnait pas

2023-09-05 20:06 UTC, LeGeek01 commented
Mais ce que je comprend pas c'est que dans mes commits j'ai pas touché à l'ent de rennes

2023-09-05 20:25 UTC, Bapt5 reviewed
Tu as modifié les ents de rennes et hubeduconnect dans ce commit

2023-09-05 20:26 UTC, Bapt5 commented
Je viens de tester celle de Rennes marche. S'il te plait laisse les si tu n'es pas sûr de toi, car ce sont des heures de travail à se tirer les cheveux avec les systèmes de connexion horribles des ENT et je n'ai pas envie que des personnes qui m'avait d'implémenter leur ENT se retrouve sans rien de fonctionnel. 
Tu as modifié enlevé l'ent de rennes et hubeduconnect dans ce commit : [sync imports with ent.py init.py](https://github.com/bain3/pronotepy/pull/255/commits/fca4637c5b32b54095978d14acba851f8b7108b4)

2023-09-05 20:27 UTC, LeGeek01 commented
Ah oui je regardais pas le bon fichier

2023-09-05 20:29 UTC, LeGeek01 commented
Wait il s'appelle reims sur ent.py

2023-09-05 20:31 UTC, LeGeek01 commented
Attend y'a un truc que je comprend pas, où est la déclaration de l'ac rennes dans ent.py ? Je l'ai dégagé aussi ?

2023-09-05 20:32 UTC, Bapt5 commented
Non celui de reims n'est pas le même. Celui de rennes ce trouve dans les complex ent comme cela y fait reference dans les import.

2023-09-05 20:33 UTC, LeGeek01 commented
Oui je viens de m'en rendre compte

2023-09-05 20:34 UTC, Bapt5 commented
Non tu ne l'as pas retiré. Mais certain ent qui ne ressemble a aucune autre ont leur propre fonction dans complex ent. 
Merci de bien vouloir regarder la structure du dossier ENT avant de mettre le désordre sans savoir ce que tu fait.

2023-09-05 20:37 UTC, LeGeek01 commented
Voilà j'ai tout corrigé normalement, mes excuses pour la confusion

2023-09-05 20:38 UTC, Bapt5 commented
Merci beaucoup! La prochaine fois n'hésite pas à me ping si tu as une question sur les ENT.

2023-09-05 20:39 UTC, LeGeek01 commented
Pour être honnête je ne sais pas ce que j'ai foutu au début pour virer l'ac rennes, je devais surrement pas avoir fait gaffe au complex ent

2023-09-05 20:40 UTC, bain3 commented
Please squash at the end, we don't have to keep all these commits.

2023-09-05 20:41 UTC, LeGeek01 commented
Ça je sais pas faire donc je vais vous laisser le faire

2023-09-05 20:42 UTC, Bapt5 commented
Penses tu pouvoir résoudre les erreurs qui ne passe pas dans les tests ?
C'est a dire vérifier si les ent existe toujours si oui voir si l'authentification à changer et si besoin mettre à jour l'authentification

2023-09-05 20:42 UTC, Bapt5 commented
@bain3 Yes no problem I will squash. We made too much commit sorry

2023-09-05 20:43 UTC, LeGeek01 commented
J'ai check un par un les ents, et tous ceux qui sont listés fonctionnent encore
L'erreur des tests vient d'où ?

2023-09-05 20:43 UTC, Bapt5 commented
> J'ai check un par un les ents, et tous ceux qui sont listés fonctionnent encore L'erreur des tests vient d'où ?

Cliques dessus tu vas voir les details je crois qu'il y a l'ent haut de seine et celui de la creuse

2023-09-05 20:45 UTC, Bapt5 commented
> Pour être honnête je ne sais pas ce que j'ai foutu au début pour virer l'ac rennes, j'ai surrement pas fait gaffe au complex ent

Oui effectivement il faut faire gaffe il y a beaucoup d'ent, il ne faut pas en oublier et il ne faut pas casser une ent dont peut être des utilisateurs se servaient

2023-09-05 20:46 UTC, LeGeek01 commented
Les tests utilisent la version demo de pronote ?

2023-09-05 20:46 UTC, LeGeek01 commented
Si oui l'erreur est toute trouvée, l'espace démo n'a pas été mis à jour vers une base 2023

2023-09-05 20:48 UTC, LeGeek01 commented
Ouais c'est ça, en gros la dernière période définie sur l'espace démo est terminée depuis les vacances de juillet, et la base n'a pas été mise à jour ce qui explique l'erreur

2023-09-05 20:49 UTC, LeGeek01 commented
Normalement quand index ferala mise à jour de la base de démo, il n'y aura plus d'erreur

2023-09-05 20:51 UTC, Bapt5 commented
> Les tests utilisent la version demo de pronote ?

Non je parle des tests pour les ENT. Et ceux ci ne vont pas se résoudre avec la mise à jour de la démo

2023-09-05 20:52 UTC, bain3 commented
No. ENT tests don't connect to the demo website it is failing somewhere in the ENT login process. [link](https://github.com/bain3/pronotepy/actions/runs/6089523695/job/16522534314?pr=255#step:5:87)

2023-09-05 20:55 UTC, LeGeek01 commented
> > Les tests utilisent la version demo de pronote ?
> 
> Non je parle des tests pour les ENT. Et ceux ci ne vont pas se résoudre avec la mise à jour de la démo

Oui je suis en train de regarder, les deux liens fonctionnent par contre j'ai remarqué qu'il manque le sélecteur de login sur l'ent creuse, est-ce que ça viendrai de la ?
Pour l'enc haut de seine je n'ai pas trouvé de problème

2023-09-05 21:02 UTC, Bapt5 commented
> Oui je suis en train de regarder, les deux liens fonctionnent par contre j'ai remarqué qu'il manque le sélecteur de login sur l'ent creuse, est-ce que ça viendrai de la ? Pour l'enc haut de seine je n'ai pas trouvé de problème

Non mais le sélecteur de login ne marche pas comme si tu cliquais. Tout se fait avec des requêtes ont imite a aucun moment les cliques d'une souris. Donc quand je fais ça je regarde avec l'onglet Réseau de l'outil de développement de mon navigateur, les requêtes faites par les ENT. Et ainsi je reconstitue ce que font les ENT. 
Je n'ai pas le temps de m'y pencher et je sens que tu n'as pas bien l'habitude avec ces méthodes de reverse engineering. 

So I suggest, if @bain3 is ok, to comment the code of `ent_creuse` and `enc_hauts_de_seine` waiting for someone to fix them

2023-09-05 21:03 UTC, bain3 commented
Yeah sure, they don't work anyways...

2023-09-05 21:05 UTC, LeGeek01 commented
> > Oui je suis en train de regarder, les deux liens fonctionnent par contre j'ai remarqué qu'il manque le sélecteur de login sur l'ent creuse, est-ce que ça viendrai de la ? Pour l'enc haut de seine je n'ai pas trouvé de problème
> 
> Non mais le sélecteur de login ne marche pas comme si tu cliquais. Tout se fait avec des requêtes ont imite a aucun moment les cliques d'une souris. Donc quand je fais ça je regarde avec l'onglet Réseau de l'outil de développement de mon navigateur, les requêtes faites par les ENT. Et ainsi je reconstitue ce que font les ENT. Je n'ai pas le temps de m'y pencher et je sens que tu n'as pas bien l'habitude avec ces méthodes de reverse engineering.
> 
> So I suggest, if @bain3 is ok, to comment the code of `ent_creuse` and `enc_hauts_de_seine` waiting for someone to fix them

je dis ça parce que je vois tous les autres ent avec ce sélecteur et il y a que l'ent de creuse qui ne l'a pas
et pour enc hauts de seine j'ai peut-être trouvé le soucis, le code appelle le form de login avec l'id "auth_form" sauf que quand je regarde dans le F12 ce n'est pas "auth-form" mais "kc-form-login", je suppose donc que ça viens de là

2023-09-05 21:09 UTC, LeGeek01 commented
si mes hypothèses sont correctes, le test ent ne devrait plus retourner d'erreur

2023-09-05 21:16 UTC, LeGeek01 commented
ok donc l'ent creuse est fixé, par conte pourquoi le black formatter se met à fail maintenant

2023-09-05 21:23 UTC, Bapt5 commented
Merci bien vu pour l'ent creuse, c'était exactement ça l'erreur.
C'est bon j'ai rajouté l ent creuse en educonnect et j'ai run black.  Et normalement j'ai rajouté la doc pour les fonctions que j'ai mise. Donc on est bon.
Tout est bon pour toi ?

2023-09-05 21:25 UTC, LeGeek01 commented
si tout fonctionne on est parfait

2023-09-05 21:27 UTC, merged

2023-09-05 21:30 UTC, LeGeek01 commented
@Bapt5 du coup tu vas faire une nouvelle release pour fixer les ent ?

2023-09-05 21:30 UTC, bain3 commented
Perfect, thank you both!

2023-09-05 21:31 UTC, Bapt5 commented
> @Bapt5 du coup tu vas faire une nouvelle release pour fixer les ent ?

Je vais laisser @bain3 faire cela

2023-09-05 21:31 UTC, LeGeek01 commented
dac pas de soucis

2023-09-05 21:31 UTC, LeGeek01 commented
ravi d'avoir pu vous aider :)

2023-09-05 21:31 UTC, Bapt5 commented
> Perfect, thank you both!

No problem 😉

2023-09-07 20:57 UTC, lesensei commented
Bonjour à tous,

Je me permets de poser la question ici, parce que ce n'est pas clair pour moi.

Est-ce que l'ENT des Hauts-de-Seine est censé fonctionner suite à cette PR ?

Le commentaire de @Bapt5 (https://github.com/bain3/pronotepy/pull/255#issuecomment-1707306213) me donne l'impression qu'il a été abandonné (et la mise en commentaire du code dans ent.py semble aller dans ce sens).

Mais dans le même temps, le commentaire de @LeGeek01 (https://github.com/bain3/pronotepy/pull/255#issuecomment-1707310029) laisse entendre qu'il a réglé le problème, et c'est peut-être moi qui ne comprend pas comment me connecter dans ce département désormais, du coup.

S'il faut comme je le crois corriger le code pour que ça fonctionne dans les Hauts-de-Seine, j'essayerai de faire le nécessaire !

Merci :-)

2023-09-07 21:50 UTC, Bapt5 commented
Non il n'a pas été corrigé car la modification de @LeGeek01 ne fonctionnait pas